server.port=8090

spring.datasource.url=jdbc:h2:file:./data/in3d;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
